import type { ProductConfig } from "../config";
import { compareStrings, isoDate, mdTable, monthYear, plural } from "../format";
import { CLASS_LABELS, REASON_LABELS, ROUTE_LABELS, routeArticle, VERDICT_LABELS } from "../labels";
import { type CraScopeResult, documentationRetainedUntil, supportPeriodProblems } from "../rules";
import type { BomPackage } from "../sbom/cyclonedx";
import type { ScanReport } from "../scan/scan";
import { CLI_VERSION } from "../version";

/** Marker for everything only the manufacturer can supply; `grep -r "TODO(vendor)"` lists them. */
export const TODO = "TODO(vendor)";

export interface DocsInput {
  product: ProductConfig;
  version: string;
  releaseDate: Date;
  now: Date;
  scope: CraScopeResult;
  sbom: {
    sha256: string;
    serialNumber: string;
    generator: "syft" | "builtin";
    lockfiles: string[];
    packages: BomPackage[];
    direct: BomPackage[];
  };
  /** null when the scan could not run; `scanError` says why. */
  scan: ScanReport | null;
  scanError: string | null;
  placeholders: string[];
}

const BLOCK = /<!-- cra:vendor ([A-Za-z0-9._-]+) -->\n([\s\S]*?)\n?<!-- cra:end \1 -->/g;

/**
 * Sections the manufacturer writes. Their content is carried over from the
 * previous version of the file on every regeneration; everything outside
 * them is regenerated.
 */
export class VendorBlocks {
  private readonly existing = new Map<string, string>();

  constructor(previous: string | null) {
    for (const match of previous?.matchAll(BLOCK) ?? []) {
      if (match[1] !== undefined) this.existing.set(match[1], match[2] ?? "");
    }
  }

  body(id: string, fallback: string): string {
    return this.existing.get(id) ?? fallback;
  }

  block(id: string, fallback: string): string {
    return `<!-- cra:vendor ${id} -->\n${this.body(id, fallback)}\n<!-- cra:end ${id} -->`;
  }
}

export function header(title: string, input: DocsInput, purpose: string): string {
  const lines = [
    `# ${title}`,
    "",
    `**Product:** ${input.product.name} ${input.version} | **Manufacturer:** ${input.product.manufacturer.name} | **Regulation (EU) 2024/2847 (Cyber Resilience Act)**`,
    "",
    `> **Template generated by cra ${CLI_VERSION} (ReleaseKeep) - not legal advice.** ${purpose} The manufacturer completes, checks and owns this document; generating it does not demonstrate conformity. Text between \`cra:vendor\` markers is yours and survives regeneration; everything else is rewritten from cra.yml, the SBOM and the vulnerability scan on every run. Open items are marked \`${TODO}\`.`,
  ];
  const banner = scopeBanner(input);
  return [...lines, ...(banner ? ["", banner] : [])].join("\n");
}

function scopeBanner(input: DocsInput): string | null {
  const { scope, product } = input;
  const reasons = scope.reasons.map((r) => REASON_LABELS[r] ?? r).join(" ");
  if (scope.verdict === "out_of_scope") {
    return `> **Scope triage: out of scope.** ${reasons} On that basis the CRA does not require this document; it is kept so the reasoning and your security practice stay on record. Re-run the triage whenever monetisation or distribution changes.`;
  }
  if (scope.verdict === "steward_regime") {
    return "> **Scope triage: open-source software steward (Art. 24).** Stewards put in place a cybersecurity policy, cooperate with market surveillance authorities and report actively exploited vulnerabilities (Art. 24(1)-(3)). They do not draw up an EU declaration of conformity or affix the CE marking (Recital 19).";
  }
  if (scope.legacyProduct && product.placedOnMarketAt) {
    return `> **Legacy product (Art. 69(2)-(3)).** First placed on the market on ${isoDate(product.placedOnMarketAt)}, before 11 December 2027: until it is substantially modified (Art. 3(30)) only the Art. 14 reporting obligations apply. The other records prepare for that modification.`;
  }
  return null;
}

export function supportFacts(input: DocsInput) {
  const { product } = input;
  const placed = product.placedOnMarketAt ?? input.releaseDate;
  return {
    placed,
    placedIsEstimate: product.placedOnMarketAt === null,
    problems: supportPeriodProblems({
      placedOnMarketAt: placed,
      supportEndsAt: product.supportEndsAt,
      ...(product.expectedUseYears !== null ? { expectedUseYears: product.expectedUseYears } : {}),
    }),
    retainedUntil: documentationRetainedUntil(placed, product.supportEndsAt),
  };
}

export function scopeRows(input: DocsInput): Array<[string, string]> {
  const { scope } = input;
  return [
    ["Scope verdict", VERDICT_LABELS[scope.verdict]],
    ["Product class", CLASS_LABELS[scope.productClass]],
    [
      "Conformity assessment route",
      scope.route ? `${ROUTE_LABELS[scope.route]} (${routeArticle(scope)})` : "Not applicable",
    ],
    [
      "Support period ends",
      `${monthYear(input.product.supportEndsAt)} (${isoDate(input.product.supportEndsAt)})`,
    ],
  ];
}

export function keyValueTable(rows: Array<[string, string]>): string {
  return mdTable(["Field", "Value"], rows);
}

export function sbomSummary(input: DocsInput): string {
  const { sbom } = input;
  const byType = new Map<string, number>();
  const byScope = new Map<string, number>();
  for (const p of sbom.packages) {
    byType.set(p.type, (byType.get(p.type) ?? 0) + 1);
    const scope = p.scope ?? "unspecified";
    byScope.set(scope, (byScope.get(scope) ?? 0) + 1);
  }
  const list = (m: Map<string, number>) =>
    [...m]
      .sort(([a], [b]) => compareStrings(a, b))
      .map(([k, n]) => `${k} ${n}`)
      .join(", ") || "none";
  return keyValueTable([
    ["File", "[sbom.cdx.json](sbom.cdx.json) (CycloneDX 1.6 JSON)"],
    ["SHA-256", `\`${sbom.sha256}\``],
    ["Serial number", `\`${sbom.serialNumber}\``],
    ["Components", `${sbom.packages.length} (${sbom.direct.length} direct)`],
    ["By package type", list(byType)],
    ["By scope", list(byScope)],
    [
      "Generated from",
      sbom.generator === "syft"
        ? "Syft directory scan"
        : sbom.lockfiles.map((f) => `\`${f}\``).join(", ") || "-",
    ],
  ]);
}

export function scanSummary(input: DocsInput): string {
  const { scan } = input;
  if (!scan) return `Vulnerability scan not performed: ${input.scanError ?? "unknown error"}.`;
  const s = scan.summary;
  const lines = [
    keyValueTable([
      [
        "Sources",
        "OSV.dev (by package URL), cross-referenced with the CISA Known Exploited Vulnerabilities catalog",
      ],
      ["Status", scan.status],
      ["Components checked", `${scan.components.queried} of ${scan.components.total}`],
      [
        "Findings",
        `${s.total} (critical ${s.critical}, high ${s.high}, medium ${s.medium}, low ${s.low}, unrated ${s.unknown})`,
      ],
      ["Listed in CISA KEV (known exploited)", String(s.kev)],
      ["Details", "[scan.json](scan.json)"],
    ]),
  ];
  if (scan.notes.length > 0) lines.push("", ...scan.notes.map((n) => `- ${n}`));
  return lines.join("\n");
}

export function findingsTable(input: DocsInput, limit = 50): string {
  const findings = input.scan?.findings ?? [];
  if (findings.length === 0)
    return input.scan ? "No known vulnerabilities in the scanned components." : "";
  const rows = findings
    .slice(0, limit)
    .map((f) => [
      f.kev ? "yes" : "",
      f.severity + (f.score !== null ? ` ${f.score.toFixed(1)}` : ""),
      `[${f.id}](${f.url})`,
      `${f.package.name}@${f.package.version ?? "?"}`,
      f.fixedVersions.join(", ") || "no fix listed",
      f.summary,
    ]);
  const more =
    findings.length > limit
      ? `\n\n${plural(findings.length - limit, "more finding")} in [scan.json](scan.json).`
      : "";
  return mdTable(["KEV", "Severity", "Advisory", "Package", "Fixed in", "Summary"], rows) + more;
}
