import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { errnoCode } from "../errors";
import { cell, isoDateTime, mdTable } from "../format";
import { type ScanReport, scanHeadline, scanJson } from "../scan/scan";
import { CLI_VERSION } from "../version";
import { type DocsInput, keyValueTable, scopeRows, TODO, VendorBlocks } from "./common";
import { declarationOfConformity } from "./declaration";
import { supportPeriod, userInformation } from "./support";
import { riskAssessment, technicalDocumentation } from "./technical";
import { reportingRunbook, securityTxt, vulnerabilityHandling } from "./vulnerability";

/** Generated documents, in the order index.md lists them. */
export const DOCUMENTS: ReadonlyArray<{
  file: string;
  covers: string;
  render: (input: DocsInput, blocks: VendorBlocks) => string;
}> = [
  {
    file: "technical-documentation.md",
    covers: "Technical documentation (Art. 31, Annex VII)",
    render: technicalDocumentation,
  },
  {
    file: "risk-assessment.md",
    covers: "Cybersecurity risk assessment against Annex I Part I (Art. 13(2)-(4))",
    render: riskAssessment,
  },
  {
    file: "declaration-of-conformity.md",
    covers: "EU declaration of conformity, draft (Art. 28, Annex V)",
    render: declarationOfConformity,
  },
  {
    file: "vulnerability-handling.md",
    covers: "Vulnerability handling and CVD policy (Annex I Part II)",
    render: vulnerabilityHandling,
  },
  {
    file: "support-period.md",
    covers: "Support period and update availability (Art. 13(8), (9), (19))",
    render: supportPeriod,
  },
  {
    file: "user-information.md",
    covers: "Information and instructions to the user (Art. 13(18), Annex II)",
    render: userInformation,
  },
  {
    file: "reporting-runbook.md",
    covers: "Reporting actively exploited vulnerabilities and severe incidents (Art. 14)",
    render: reportingRunbook,
  },
  {
    file: "security.txt",
    covers: "Security contact for /.well-known/ (RFC 9116)",
    render: (input) => securityTxt(input),
  },
];

async function readExisting(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (errnoCode(error) === "ENOENT") return null;
    throw error;
  }
}

const countTodos = (text: string) => text.split(TODO).length - 1;

export function indexMarkdown(
  input: DocsInput,
  todos: Map<string, number>,
  scan: ScanReport | null,
): string {
  const scanText = scan
    ? `${scanHeadline(scan)}${scan.kevCatalog ? `; KEV catalog ${scan.kevCatalog.version}` : ""}`
    : `not performed: ${input.scanError ?? "unknown error"}`;
  const rows: Array<[string, string]> = [
    ["Product", input.product.name],
    ["Version", input.version],
    ["Manufacturer", input.product.manufacturer.name],
    ["Generated", `${isoDateTime(input.now)} by cra ${CLI_VERSION} (ReleaseKeep)`],
    ...scopeRows(input),
    ["SBOM", `[sbom.cdx.json](sbom.cdx.json), ${input.sbom.packages.length} components`],
    ["SBOM SHA-256", `\`${input.sbom.sha256}\``],
    ["Vulnerability scan", `[scan.json](scan.json): ${scanText}`],
    [
      "cra.yml placeholders",
      input.placeholders.length > 0 ? input.placeholders.join(", ") : "none",
    ],
  ];
  const total = [...todos.values()].reduce((a, b) => a + b, 0);
  return [
    `# CRA records - ${input.product.name} ${input.version}`,
    "",
    "Records for Regulation (EU) 2024/2847 (Cyber Resilience Act), regenerated by cra (ReleaseKeep) on every release so that the git history of this directory is the audit trail.",
    "",
    keyValueTable(rows),
    "",
    "## Documents",
    "",
    mdTable(
      ["Document", "Covers", "Open vendor items"],
      [
        ...DOCUMENTS.map((d) => [`[${d.file}](${d.file})`, d.covers, todos.get(d.file) ?? 0]),
        [
          "[sbom.cdx.json](sbom.cdx.json)",
          "Software bill of materials, CycloneDX 1.6 (Annex I Part II(1))",
          "-",
        ],
        ["[scan.json](scan.json)", "OSV and CISA KEV findings for the SBOM", "-"],
      ],
    ),
    "",
    `${cell(total)} open items are marked \`${TODO}\`: \`grep -rn "${TODO}" .\` lists them.`,
    "",
    "## What these documents are, and are not",
    "",
    "- They are templates and evidence the manufacturer completes, reviews and signs. Generating them is not a conformity assessment and does not make the product compliant.",
    "- The scope verdict is triage with article references, not legal advice. Check it against the regulation and the Commission's guidance.",
    "- The SBOM and the scan cover the dependencies found in lockfiles (or by Syft); they say nothing about the product's own code.",
    "- Text between `cra:vendor` markers is kept on regeneration; edits elsewhere are overwritten.",
    "",
  ].join("\n");
}

/**
 * Writes the generated records into `dir`, overwriting only the files cra
 * owns and keeping the manufacturer's sections. Returns the files written and
 * the number of open `TODO(vendor)` items in them.
 */
export async function writeDocs(
  dir: string,
  input: DocsInput,
  sbomText: string,
  scan: ScanReport | null,
): Promise<{ files: string[]; openItems: number }> {
  await mkdir(dir, { recursive: true });
  const todos = new Map<string, number>();
  const written: string[] = [];
  for (const doc of DOCUMENTS) {
    const path = join(dir, doc.file);
    const content = doc.render(input, new VendorBlocks(await readExisting(path)));
    todos.set(doc.file, countTodos(content));
    await writeFile(path, content.endsWith("\n") ? content : `${content}\n`);
    written.push(doc.file);
  }
  await writeFile(join(dir, "sbom.cdx.json"), sbomText);
  written.push("sbom.cdx.json");
  // A failed scan still replaces the previous release's results, so nothing stale survives.
  const scanText = scan
    ? scanJson(scan)
    : `${JSON.stringify(
        {
          // "cra-kit" is the tool id the hosted service validates in scan.json; keep it.
          tool: { name: "cra-kit", version: CLI_VERSION },
          status: "error",
          notes: [input.scanError ?? "unknown error"],
          findings: [],
        },
        null,
        2,
      )}\n`;
  await writeFile(join(dir, "scan.json"), scanText);
  written.push("scan.json");
  await writeFile(join(dir, "index.md"), indexMarkdown(input, todos, scan));
  written.push("index.md");
  return { files: written, openItems: [...todos.values()].reduce((a, b) => a + b, 0) };
}
