import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { type DocsInput, TODO } from "../docs/common";
import { writeDocs } from "../docs/generate";
import { EXIT, NetworkError, UsageError } from "../errors";
import { cell, mdTable, monthYear, plural, textTable } from "../format";
import { asRecord } from "../guards";
import { CLASS_LABELS, VERDICT_LABELS } from "../labels";
import {
  assessScope,
  displayPath,
  type GlobalOptions,
  generateSbom,
  type Io,
  loadProject,
  outputDir,
  type Project,
  productVersion,
  type SbomResult,
  scanBom,
} from "../project";
import type { CraScopeResult } from "../rules";
import { bomPackages } from "../sbom/cyclonedx";
import { exceedsThreshold } from "../scan/findings";
import { type ScanReport, scanHeadline, scanJson } from "../scan/scan";

function printWarnings(project: Project, warnings: string[]): void {
  if (project.options.quiet) return;
  for (const w of warnings) project.io.stderr(`warning: ${w}\n`);
}

export async function sbomCommand(
  options: GlobalOptions,
  io: Io,
  out: string | undefined,
): Promise<number> {
  const project = await loadProject(options, io);
  const sbom = await generateSbom(project, productVersion(project));
  printWarnings(project, sbom.warnings);
  if (out === "-") {
    io.stdout(sbom.text);
    return EXIT.ok;
  }
  const path = out ? resolve(project.cwd, out) : resolve(outputDir(project), "sbom.cdx.json");
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, sbom.text);
  const summary = {
    path: displayPath(project.io.cwd, path),
    generator: sbom.generator,
    components: sbom.bom.components.length,
    direct: sbom.directCount,
    sha256: sbom.sha256,
    lockfiles: sbom.lockfiles,
  };
  if (options.json) io.stdout(`${JSON.stringify(summary, null, 2)}\n`);
  else if (!options.quiet) {
    io.stdout(
      `Wrote ${summary.path}: CycloneDX 1.6, ${plural(summary.components, "component")} (${summary.direct} direct), ` +
        `${sbom.generator === "syft" ? "generated by syft" : `from ${sbom.lockfiles.join(", ")}`}\nSHA-256 ${sbom.sha256}\n`,
    );
  }
  return EXIT.ok;
}

export function findingsText(report: ScanReport): string {
  const s = report.summary;
  const lines = [
    `Scanned ${report.components.queried} of ${report.components.total} components against OSV.dev and CISA KEV (${report.status}).`,
  ];
  if (report.findings.length > 0) {
    lines.push(
      "",
      textTable(
        ["SEVERITY", "KEV", "ID", "PACKAGE", "FIXED IN"],
        report.findings.map((f) => [
          f.severity + (f.score !== null ? ` ${f.score.toFixed(1)}` : ""),
          f.kev ? "KEV" : "",
          f.id,
          `${f.package.name}@${f.package.version ?? "?"}`,
          f.fixedVersions.join(", ") || "-",
        ]),
      ),
    );
  }
  lines.push(
    "",
    `${plural(s.total, "finding")}: ${s.kev} known exploited (KEV), ${s.critical} critical, ${s.high} high, ${s.medium} medium, ${s.low} low, ${s.unknown} unrated.`,
    ...report.notes.map((n) => `note: ${n}`),
  );
  return `${lines.join("\n")}\n`;
}

export async function scanCommand(
  options: GlobalOptions,
  io: Io,
  sbomPath: string | undefined,
): Promise<number> {
  const project = await loadProject(options, io);
  let bom: unknown;
  if (sbomPath) {
    const path = resolve(project.cwd, sbomPath);
    try {
      bom = JSON.parse(await readFile(path, "utf8"));
    } catch (error) {
      throw new UsageError(
        `cannot read the SBOM at ${displayPath(project.io.cwd, path)}: ${String(error)}`,
      );
    }
    if (asRecord(bom).bomFormat !== "CycloneDX") {
      throw new UsageError(`${displayPath(project.io.cwd, path)} is not a CycloneDX JSON document`);
    }
  } else {
    const sbom = await generateSbom(project, productVersion(project));
    printWarnings(project, sbom.warnings);
    bom = sbom.bom;
  }
  const report = await scanBom(project, bom);
  const failed = exceedsThreshold(report.findings, project.failOn);
  if (options.json) {
    const body = JSON.parse(scanJson(report));
    io.stdout(
      `${JSON.stringify({ ...body, failOn: project.failOn, exceedsThreshold: failed }, null, 2)}\n`,
    );
  } else if (!options.quiet) {
    io.stdout(findingsText(report));
    if (failed) io.stdout(`Findings exceed scan.failOn = ${project.failOn}.\n`);
  }
  return failed ? EXIT.findings : EXIT.ok;
}

interface PipelineResult {
  project: Project;
  version: string;
  scope: CraScopeResult;
  sbom: SbomResult;
  scan: ScanReport | null;
  scanError: NetworkError | null;
  dir: string;
  files: string[];
  openItems: number;
}

/** sbom + scan + docs; a network failure is recorded in the documents and reported afterwards. */
async function runPipeline(options: GlobalOptions, io: Io): Promise<PipelineResult> {
  const project = await loadProject(options, io);
  const version = productVersion(project);
  const scope = assessScope(project);
  const sbom = await generateSbom(project, version);
  printWarnings(project, sbom.warnings);
  let scan: ScanReport | null = null;
  let scanError: NetworkError | null = null;
  try {
    scan = await scanBom(project, sbom.bom);
  } catch (error) {
    if (!(error instanceof NetworkError)) throw error;
    scanError = error;
  }
  const packages = bomPackages(sbom.bom);
  const directRefs = new Set(sbom.bom.dependencies[0]?.dependsOn ?? []);
  const input: DocsInput = {
    product: project.config.product,
    version,
    releaseDate: project.releaseDate,
    now: project.now,
    scope,
    sbom: {
      sha256: sbom.sha256,
      serialNumber: sbom.bom.serialNumber,
      generator: sbom.generator,
      lockfiles: sbom.lockfiles,
      packages,
      direct: packages.filter((p) => directRefs.has(p.purl)),
    },
    scan,
    scanError: scanError ? (scanError.message.split("\n")[0] ?? "network error") : null,
    placeholders: project.placeholders,
  };
  const dir = outputDir(project);
  const { files, openItems } = await writeDocs(dir, input, sbom.text, scan);
  return { project, version, scope, sbom, scan, scanError, dir, files, openItems };
}

export async function docsCommand(options: GlobalOptions, io: Io): Promise<number> {
  const result = await runPipeline(options, io);
  const { project, scanError } = result;
  if (options.json) {
    io.stdout(
      `${JSON.stringify({ outputDir: displayPath(project.io.cwd, result.dir), files: result.files, openVendorItems: result.openItems }, null, 2)}\n`,
    );
  } else if (!options.quiet) {
    io.stdout(
      `Wrote ${result.files.length} files to ${displayPath(project.io.cwd, result.dir)}/ (${plural(result.openItems, "open vendor item")} marked ${TODO}).\n`,
    );
  }
  // The documents never depend on the network: an unreachable feed is noted in them, not fatal.
  if (scanError) {
    io.stderr(`warning: vulnerability scan not performed: ${scanError.message.split("\n")[0]}\n`);
  }
  return EXIT.ok;
}

export function summaryMarkdown(result: PipelineResult, exitCode: number): string {
  const { project, scope, scan, sbom } = result;
  const product = project.config.product;
  const lines = [
    `## CRA records - ${product.name} ${result.version}`,
    "",
    mdTable(
      ["Record", "Result"],
      [
        ["Scope verdict", VERDICT_LABELS[scope.verdict]],
        ["Product class", CLASS_LABELS[scope.productClass]],
        ["Support ends", monthYear(product.supportEndsAt)],
        [
          "SBOM",
          `${sbom.bom.components.length} components, SHA-256 \`${sbom.sha256.slice(0, 16)}...\``,
        ],
        [
          "Vulnerabilities",
          scan
            ? scanHeadline(scan)
            : `scan failed: ${result.scanError?.message.split("\n")[0] ?? ""}`,
        ],
        [
          "Fail threshold",
          `${project.failOn}${exitCode === EXIT.findings ? " - **exceeded**" : ""}`,
        ],
        ["Open vendor items", String(result.openItems)],
      ],
    ),
  ];
  if (scan && scan.findings.length > 0) {
    lines.push(
      "",
      mdTable(
        ["Severity", "KEV", "Advisory", "Package", "Fixed in"],
        scan.findings
          .slice(0, 100)
          .map((f) => [
            f.severity + (f.score !== null ? ` ${f.score.toFixed(1)}` : ""),
            f.kev ? "yes" : "",
            `[${f.id}](${f.url})`,
            `${f.package.name}@${f.package.version ?? "?"}`,
            f.fixedVersions.join(", ") || "-",
          ]),
      ),
    );
    if (scan.findings.length > 100)
      lines.push("", `${cell(scan.findings.length - 100)} more in scan.json.`);
  }
  return `${lines.join("\n")}\n`;
}

export async function allCommand(
  options: GlobalOptions,
  io: Io,
  files: { summary?: string; outputs?: string },
): Promise<number> {
  const result = await runPipeline(options, io);
  const { project, scope, scan, sbom, scanError } = result;
  const failed = scan ? exceedsThreshold(scan.findings, project.failOn) : false;
  const exitCode = scanError ? EXIT.network : failed ? EXIT.findings : EXIT.ok;
  const outDir = displayPath(project.io.cwd, result.dir);

  if (files.summary)
    await appendFile(resolve(io.cwd, files.summary), summaryMarkdown(result, exitCode));
  if (files.outputs) {
    const outputs = {
      "output-dir": relative(io.cwd, result.dir) || ".",
      verdict: scope.verdict,
      findings: String(scan?.summary.total ?? 0),
      kev: String(scan?.summary.kev ?? 0),
      "exceeds-threshold": String(failed),
      "exit-code": String(exitCode),
    };
    await appendFile(
      resolve(io.cwd, files.outputs),
      Object.entries(outputs)
        .map(([k, v]) => `${k}=${v}\n`)
        .join(""),
    );
  }

  if (options.json) {
    io.stdout(
      `${JSON.stringify(
        {
          product: project.config.product.name,
          version: result.version,
          verdict: scope.verdict,
          productClass: scope.productClass,
          sbom: {
            components: sbom.bom.components.length,
            sha256: sbom.sha256,
            generator: sbom.generator,
          },
          scan: scan
            ? { status: scan.status, ...scan.summary }
            : { status: "error", error: scanError?.message },
          failOn: project.failOn,
          exceedsThreshold: failed,
          outputDir: outDir,
          files: result.files,
          openVendorItems: result.openItems,
          exitCode,
        },
        null,
        2,
      )}\n`,
    );
  } else if (!options.quiet) {
    io.stdout(
      [
        `cra: ${project.config.product.name} ${result.version}`,
        `  scope      ${VERDICT_LABELS[scope.verdict]}; ${CLASS_LABELS[scope.productClass]}`,
        `  sbom       ${plural(sbom.bom.components.length, "component")} (${sbom.generator}), sha256 ${sbom.sha256.slice(0, 16)}...`,
        `  scan       ${scan ? scanHeadline(scan) : "failed (network)"}`,
        `  documents  ${result.files.length} files in ${outDir}/, ${plural(result.openItems, "open vendor item")}`,
        failed
          ? `  result     findings exceed scan.failOn = ${project.failOn}`
          : `  result     ok (failOn ${project.failOn})`,
        "",
      ].join("\n"),
    );
    if (scan && scan.findings.length > 0 && failed) io.stdout(findingsText(scan));
  }
  if (scanError) io.stderr(`error: ${scanError.message}\n`);
  return exitCode;
}
